# Use DecapBridge auth
backend:
  name: decap-bridge
  bridge_url: https://gateway.decapbridge.com        # keep this line
  repo: SarahKMay/baseweb                            # <— your GitHub repo owner/name
  branch: main

# Optional niceties
site_url: https://sktestweb.netlify.app
display_url: https://sktestweb.netlify.app
logo_url: https://decapbridge.com/decapcms-with-bridge.svg
publish_mode: editorial_workflow

# Local editing support (optional; run: npx decap-server && npm start)
local_backend: true

# Media paths (make sure these paths exist in your repo)
media_folder: "src/assets/images/blog"      # files saved here in Git
public_folder: "/assets/images/blog"        # how the site references them

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"              # ensure this folder exists
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "url", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
